name: Build Executables

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
#         os: [macos-latest, ubuntu-latest, windows-latest]
        os: [macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Volta
        uses: volta-cli/action@v1
        
      - name: Install Deps 
        run: "npm install"
        shell: bash
        
      - name: Build 
        run: "npm run make"
        shell: bash
        
      - uses: actions/upload-artifact@v2
        with:
          if: matrix.os == 'windows-latest'
          name: windows.zip
          path: ./out/make/squirrel.windows/x64/
