name: Build Executables

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
#         os: [macos-latest, ubuntu-latest, windows-latest]
        os: [self-hosted-macOS, self-hosted-windows]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Volta
        uses: volta-cli/action@v1

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-

      - name: Install Deps
        run: "npm install"
        shell: bash

      - name: Build
        run: "npm run make"
        shell: bash

      - name: Add Windows certificate
        if: matrix.os == 'self-hosted-windows'
        id: write_file
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'win-certificate.pfx'
          encodedString: ${{ secrets.WINDOWS_PFX_CERT }}

      - uses: actions/upload-artifact@v2
        name: Upload Windows artifacts
        if: matrix.os == 'self-hosted-windows'
        with:
          name: windows.zip
          path: ./out/make/squirrel.windows/x64/

      - uses: actions/upload-artifact@v2
        name: Upload macOS artifacts
        if: matrix.os == 'self-hosted-macOS'
        with:
          name: macOS.zip
          path: ./out/make/zip/darwin/x64/
