name: Build release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [self-hosted-macOS, self-hosted-windows]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Volta
        uses: volta-cli/action@v1

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-modules-

      - name: Install Deps
        run: "npm install"

      - name: Add Windows certificate
        if: matrix.os == 'self-hosted-windows'
        id: write_file
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'win-certificate.pfx'
          encodedString: ${{ secrets.WINDOWS_PFX_CERT }}

      - name: Add MacOS certs
        if: matrix.os == 'self-hosted-macOS'
        run: chmod +x bin/add-macos-cert.sh && ./bin/add-macos-cert.sh
        env:
          MACOS_PFX_CERT: ${{ secrets.MACOS_PFX_CERT }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}

      - name: Build
        env:
          WINDOWS_PFX_FILE: ${{ steps.write_file.outputs.filePath }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
        run: "npm run electron:build"

      # Upload build file to the release as an asset
      - name: Upload Windows Files
        if: matrix.os == 'self-hosted-windows'
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: ./out/make/squirrel.windows/x64/**
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload Windows Files
        if: matrix.os == 'self-hosted-macOS'
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: ./out/make/zip/darwin/x64/**
          tag: ${{ github.ref }}
          overwrite: true
